# Generated by Django 3.2.6 on 2021-08-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarianmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='librarianmodel',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='librarianmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='librarianmodel',
            name='username',
        ),
    ]
