# Generated by Django 3.2.6 on 2021-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20210821_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarianmodel',
            name='enroll_code',
        ),
        migrations.AddField(
            model_name='librarianmodel',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='librarianmodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
