# Generated by Django 3.2.6 on 2021-08-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_auto_20210821_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarianmodel',
            name='enroll_code',
        ),
        migrations.RemoveField(
            model_name='librarianmodel',
            name='mobilenumber',
        ),
    ]
