# Generated by Django 3.2.6 on 2021-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20210821_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarianmodel',
            name='enroll_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='librarianmodel',
            name='mobilenumber',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='librarianmodel',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='librarianmodel',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
