# Generated by Django 3.2.6 on 2021-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='publisher',
        ),
    ]
