# Generated by Django 3.2.6 on 2021-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210821_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
