# Generated by Django 3.2.6 on 2021-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='publisher',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
